image: docker

services:
    - docker:dind

stages:
    - deploy

deploy:
    stage: deploy
    only:
        - master
    script:
        - apt-get install -y python-pip
        - pip install docker-compose
        - docker-compose up -d --build
